# Generated by Django 4.0.3 on 2022-03-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Nft',
        ),
    ]
