# Generated by Django 4.0.3 on 2022-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0002_rename_todo_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='url',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='sig',
            field=models.TextField(default='a'),
        ),
    ]
