# Generated by Django 4.0.3 on 2022-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0003_nft_url_alter_nft_sig'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
