# Generated by Django 4.0.3 on 2022-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0004_nft_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='erc1155',
            field=models.BooleanField(default=False),
        ),
    ]
