# Generated by Django 4.0.3 on 2022-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0005_nft_erc1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nft1155',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenId', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('url', models.TextField(default='a')),
                ('sold', models.BooleanField(default=True)),
                ('amount', models.IntegerField(default=1)),
                ('amountLeft', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='nft',
            name='erc1155',
            field=models.BooleanField(default=True),
        ),
    ]
