# Generated by Django 4.0.3 on 2022-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0006_nft1155_alter_nft_erc1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='royal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nft1155',
            name='royal',
            field=models.IntegerField(default=1),
        ),
    ]
